apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: spring-boot-k-s-skaffold-demo
build:
  artifacts:
    - image: spring-boot-k8s-skaffold-demo
      jib: { }
manifests:
  rawYaml:
    - k8s-deployment.yml
    - k8s-service.yml
deploy:
  kubectl:
    manifests:
      - k8s-*
